#!/bin/bash

#echo "$1"
escapedFind=$(echo "$1"|sed 's/[]\/$*.^|[]/\\&/g')  # don't escape parentheses when using bsd sed
escapedReplace=$(echo "$2"|sed 's/[]\/$*.^|[]/\\&/g')
#echo "$escapedFind"

# I know this usage of cat bugs some people, but fuck em
#cat - | sed "s/$escapedFind/$escapedReplace/g"
sed "s/$escapedFind/$escapedReplace/g"